"""Fixed lines the agent says word for word (agent.md §6), in English and Spanish.

They're spoken with ``session.say``, not generated by the LLM, so they're fast,
cost nothing and never vary.
"""

from intake.core.speech import SpokenLanguage

# The greeting in two parts: the opener (who's calling whom, and that it's a
# virtual assistant) can't be interrupted; the rest can.
GREETING_OPENER: dict[SpokenLanguage, str] = {
    "English": "Hi, thanks for calling {clinic_name}. "
    "This is {agent_name}, the clinic's virtual assistant.",
    "Spanish": "Hola, gracias por llamar a {clinic_name}. "
    "Habla {agent_name}, la asistente virtual de la clínica.",
}
GREETING_REST: dict[SpokenLanguage, str] = {
    "English": "I can get you registered as a new patient in just a few minutes. "
    "To start, what's your first and last name?",
    "Spanish": "Puedo registrarle como paciente nuevo en solo unos minutos. "
    "Para empezar, ¿cuál es su nombre y apellido?",
}


def greeting(language: SpokenLanguage, *, clinic_name: str, agent_name: str) -> tuple[str, str]:
    """The greeting's opener and the rest of it, with the names filled in."""
    names = {"clinic_name": clinic_name, "agent_name": agent_name}
    return GREETING_OPENER[language].format(**names), GREETING_REST[language].format(**names)


STILL_THERE: dict[SpokenLanguage, str] = {
    "English": "Are you still there?",
    "Spanish": "¿Sigue ahí?",
}
SILENCE_GOODBYE: dict[SpokenLanguage, str] = {
    "English": "It sounds like we got disconnected. Feel free to call back anytime. Goodbye!",
    "Spanish": "Parece que se cortó la llamada. Puede volver a llamar cuando quiera. ¡Adiós!",
}

# Instructions for the LLM (not spoken as is) when the call reaches MAX_CALL_MINUTES.
TIME_LIMIT = (
    "The call has reached its time limit, so wrap up now, in the caller's language. "
    "Call end_call, then: if commit_record already returned saved, say a warm "
    "one-sentence goodbye; otherwise apologize and say the clinic's staff will call "
    "them back at their phone number to finish."
)

# Instructions for the one-off LLM call that summarizes a finished call for staff.
SUMMARY = (
    "Summarize this clinic phone call for the front desk in two or three plain English "
    "sentences: who called, what was done (registered, updated, or appointment booked) "
    "and anything staff should follow up on. No lists, no ids."
)
